[window]
decorations = "None"
opacity = 0.9

[font]
size = 15

[env]
TERM = "xterm-256color"

[window.dimensions]
columns = 130
lines = 35

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
